print('Введите любую фразу, состоящую из двух слов:')
my_string=input()
print('Длина фразы:',(len(my_string)),'символов')
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(" ", ""))
print(my_string[0])
print(my_string[-1])
print('Вы молодец!')